language: erlang
otp_release:
  - 19.3
  - 20.0
before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
script:
  - ./rebar3 update
  - make compile
  - make test
  - make xref
  - make dialyzer
  - make lint
sudo: false
