language: erlang
otp_release:
  - 19.3
  - 20.0
cache:
  directories:
  - $HOME/otp/19.3
  - $HOME/otp/20.0
  - $HOME/.cache/rebar3
  - _plt
before_script:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
script:
  - ./rebar3 update
  - make travis
after_success:
  - make coveralls
  - make distclean
after_failure:
  - make distclean
sudo: false
addons:
    artifacts: true
    artifacts:
        s3_region: "eu-west-1"
        paths:
            - ./priv
        debug: true
